name=APSystem_ESP32_ECU
version=0.0.0
author=TobiasTTM <tobiast.t.m@hotmail.com>
maintainer=TobiasTTM <tobiast.t.m@hotmail.com>
sentence=Library for comunicating with APSystems inverters using ther native Zigbee network.
paragraph=This Library is builr around a ESP32C5 but will brobobly work with all ESP32 with native IEEE_802.15.4 support like C6 and H2.
category=Communication
url=https://github.com/TobiasTTM/APSystem_ESP32_ECU
architectures=esp32
includes=APSystems.h
depends=esp_ieee802154
